### ISSUE TITLE
ViewHelper classes should not be final

### ISSUE THREAD

**Issue by dmitryd** [sitegeist/sms-responsive-images#101]
If they are final, they cannot be further extended by custom extensions. They were not final before and making them final breaks compatibility. Now we either have to patch your extension, or make a local copy removing `final`.

Please, remove `final` from viewhelpers because it does not add any value but only restricts inheritance.

This is about `typo3v12` branch.

Thanks!

**Comment by s2b** [comment]
The problem is that with TYPO3 v12 declaring the core ViewHelpers as final, they can introduce breaking changes in-between major versions, see:

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.5/Important-95298-FluidViewhelpersWillBeDeclaredFinalInV12.html

My intention was to stay compatible with TYPO3 core, which means that the internal implementation of the ViewHelpers can change and thus they should not be extendable.

What is your use case to extend the included ViewHelpers? Maybe this could be added to the extension or could be solved with a better API (e. g. Signal/Slot)?

**Comment by dmitryd** [comment]
We add support for webp and make images to use webp by default by making `fileExtrension` default to `webp`. I do not think this would be generally universal change.

If core decided to declare all viewhelpers final and thus disallow people to build upon core viewhelpers, it only will cause copying of those viewhelpers to "user space" and prevent people from using proper OOP. It will also make harder to fix any kind of security issues inside copied viewhelpers. Bad decision in my opinion...

**Comment by dmitryd** [comment]
Added a TYPO3 ticket: https://forge.typo3.org/issues/100196

**Comment by s2b** [comment]
> We add support for webp and make images to use webp by default by making `fileExtrension` default to `webp`. I do not think this would be generally universal change.

Would it help to add a PSR-14 Event to the `initializeArguments()` method? Then you could use `overrideArgument()` to set `webp` as the default file extension.

**Comment by s2b** [comment]
Ok. Just let me know if I should add the event or something similar.

**Comment by LeoniePhiline** [comment]
For avif / webp support, simply configure nginx to inspect the `Accept-Encoding` HTTP header and respond with an avif / webp image for every jpeg request.

All you need is `image.jpg`, `image.jpg.avif` and `image.jpg.webp` next to each other in your file tree. (Or put other image encodings into different directories - as you like.)

Prefer avif for all browsers that support it. Fall back to webp for some. Fall back to jpg for the rest. No need to edit any viewhelpers.

**Comment by dmitryd** [comment]
@LeoniePhiline This requires additional packages on the server, which is not the easiest thing to do in our environment. TYPO3 GraphicsMagic is capable of making webp, so we can simply use standard TYPO3 functions without any external packages. avif - yes, good, but gm does not support it and it takes im 39 times longer to write an avif file than a webp file (useless).

So for now we prefer to stay with webp. This is the most practical at the moment.
