### ISSUE TITLE
example for dpi related setting / src

### ISSUE THREAD

**Issue by DanielRuf** [sitegeist/sms-responsive-images#11]
Are there any examples for `@2x/3x/...` dpi src values?

**Comment by s2b** [comment]
You can take a look at the documentation of the ViewHelpers:
https://docs.typo3.org/typo3cms/extensions/sms_responsive_images/DeveloperManual/Index.html#srcset

To summarize: Just use `2x/...` instead of the absolute width values in the `srcset` attribute

**Comment by DanielRuf** [comment]
Understand. Thanks for the info, will bookmark the docs url. I probably oversaw this in the first place.
