### ISSUE TITLE
No real Art Direction

### ISSUE THREAD

**Issue by DanielRuf** [sitegeist/sms-responsive-images#13]
So far I would expect multiple src/file settings so we could use another image for a specific breakpoint but this is not possible in the backend. The viewhelper justs uses one file relation / src for all spurce tags.

And I do not mean the different dpi versions. Think about totally different file references per source.

**Comment by s2b** [comment]
You are absolutely right. Once I find the time to tackled the other issues, this could and should be the next step. I‘ll have to see if this can be accomplished without changes in the core.

The „long“ term goal should be to add the whole responsive images functionality to the TYPO3 core before the next LTS release arrives.

**Comment by DanielRuf** [comment]
Short question: what does the `ponyhof` label exactly mean?

**Comment by s2b** [comment]
It means that the feature is on my wish list, but that it isn‘t something that *must* be added to the extension.

**Comment by DanielRuf** [comment]
> It means that the feature is on my wish list, but that it isn‘t something that must be added to the extension.

Ah ok. This makes more sense. The label name was a bit weird when I saw it the first time. Never saw this name in all the opensource projects where I contributed. Why not use the better naming `backlog` or `feature/optional` or similar?

**Comment by s2b** [comment]
Possible solution:

* Add field `crop_variant` to sys_file_reference`
* Allow new attribute `images` for ViewHelpers which takes an array/ObjectStorage of FileReference objects
* Use different images for each `<source>`
