### ISSUE TITLE
IE11 and srcset/picture is not working

### ISSUE THREAD

**Issue by l174rd** [sitegeist/sms-responsive-images#15]
There's an issue while rendering the images only with srcset/picture attribute in IE11.
https://caniuse.com/#feat=srcset
https://caniuse.com/#feat=picture

The page isn't loading the pictures because of the incompatibility of srcset/picture. Is there a fallback built in the extension or rather how is it possible to say TYPO3 to render a fallback image?

**Comment by s2b** [comment]
If you want to achieve compatibility with IE11, you should include the picturefill.js polyfill into your site. This JavaScript library implements the missing responsive images functionality in older browsers.

https://scottjehl.github.io/picturefill/
