### ISSUE TITLE
Sizes attribute max-width instead of min-width?

### ISSUE THREAD

**Issue by rowild** [sitegeist/sms-responsive-images#16]
In the manual, shouldn't it say "max-width: 800px" in the manual, where you talk about using the sizes-parameter for the first time (in the text above 4th code block)?

Chapter "What does it do?"

```
With the sizes attribute, one can specify how big the image will be in different 
screen sizes (as defined by the responsive design of the website). In the 
example, **the image would be at most 800 pixels wide**, so the 1000 pixels 
image would never be loaded (except on high dpi screens):

<img
   src="fallback.jpg"
   srcset="
      image@400.jpg 400w,
      image@600.jpg 600w,
      image@800.jpg 800w,
      image@1000.jpg 1000w
   "
   sizes="(**min-width: 800px**) 800px, 100vw" // <-- max-width?
   alt="alternative text"
/>
```

**Comment by s2b** [comment]
From our mail conversation:

> Wenn die Viewport-Größe größer als 800px ist (also min-width: 800px), dann hat das Bild 800px Breite. Anderenfalls ist das Bild so groß wie der Viewport (also immer < 800px).

If the viewport width is bigger than 800px (min-width: 800px), the image should be 800px wide. Otherwise the image should be as wide as the viewport (< 800px).
