### ISSUE TITLE
Request for manual addition: Examples with textmedia & news

### ISSUE THREAD

**Issue by rowild** [sitegeist/sms-responsive-images#17]
Currently, the examples in the manual show solutions with the f:image viewhelper. But the most commonly used content element is most likely textmedia, which employs the "gallery" functionality.

It is totally unclear (from the manual's description) how to use - that is: modify - you extension with textmedia and different scenarios.

Also, it most probably would be great to see some examples for how to use this extension with news or any other popular extension.

It is not good to always assume good TYPO3 users (something that happens through the TYPO3 community more and more...). The manual needs to explain as clearly as possible on how to incorporate the functionality the extension provides.

Thank you!

**Comment by s2b** [comment]
If you include the static TypoScript from the extension, all fluid_styled_content elements (which includes textmedia galleries) should be working out of the box. This is the reason why the extension overwrites a Fluid template from the TYPO3 Core.

For other extensions there aren't any examples at the moment. However, in most cases you can just replace the f:image and f:media ViewHelpers used in community extensions by the ViewHelpers in this extension and then specify the responsive image attributes as described in the documentation.

In general, it really depends on the design/layout of your website how these parameters should be set. This is nothing the extension can do automatically but something that has to be done by an integrator or developer. Also, responsive images really are an advanced topic if you want to do it the right way, which is really unfortunate but is nothing I can change with this extension.
