### ISSUE TITLE
does not work with pdf (preview)

### ISSUE THREAD

**Issue by DanielRuf** [sitegeist/sms-responsive-images#23]
The default `f:media file="{file}"` works and displays the preview of the pdf file but `sms:media file="{file}"` does not work

**Comment by s2b** [comment]
I can't reproduce this issue as well. Please try the new testing page as explained in #22 and let me know if there is still a problem.

**Comment by DanielRuf** [comment]
We use TYPO3 8 ad when we use a PDF file in the backend which generates a normal image using `f:image/media` it does not produce any valid or working picture tag as it outputs the pdf extension and the browser does not accept it.

**Comment by DanielRuf** [comment]
I would not close the issue but add a label `needs info`. Closing makes it hard to track the issue in my list on GitHub.

**Comment by s2b** [comment]
It seems to me that this is not an issue with the extension because, as I mentioned, the extension behaved exactly as it should in all possible combinations in my tests.

**Comment by DanielRuf** [comment]
Will try it again and show you the code. We still had the issue with our site extension.
