### ISSUE TITLE
for lazyload it doesn't give class of lazyload to img tag

### ISSUE THREAD

**Issue by dextar1** [sitegeist/sms-responsive-images#26]
Hi,
If i enable lazyload from constant editor then it adds data-srcset attribute which is fine, but it doesn't add lazyload class to the img tag. i have to add it via typoscript using lib.contentelement.settings.responsivexyz.class = lazyload. i think most of the lazyload libraries work with lazyload class so when lazyload is enabled from the constant then data + class both things should be done.

**Comment by fredi1993** [comment]
I have made a pull request to fix this, but it's only locally for now, don't actually know how to push it so you can check it.

**Comment by s2b** [comment]
Thank you for your contribution. I already thought about adding the class name automatically. However, this would be a breaking change as it could have direct consequences on existing installations of the extension.

I will revisit this when I start working on the next major version of the extension. Until then, you need to specify the class manually (in TypoScript for default content elements and when calling the viewhelpers manually).

**Comment by s2b** [comment]
This is already fixed in develop and will be part of v2
