### ISSUE TITLE
error in validator.w3.org because of missing src-attribut

### ISSUE THREAD

**Issue by lexi80** [sitegeist/sms-responsive-images#29]
Is it possible to add the src-attribut to viewhelper? it causes an error on https://validator.w3.org "Element img is missing required attribute src."

**Comment by s2b** [comment]
Yes, this is possible. Just have a look at the `picturefill` attribute of the ViewHelpers. It is set to `true` by default which means that the extension generates the markup recommended by [picturefill.js](http://scottjehl.github.io/picturefill/). If you set the attribute to `false`, the `src` attribute will be present.

Note that you can also set the value globally for all standard content elements via TypoScript:

```
lib.contentElement.settings.tx_smsresponsiveimages.picturefill = 0
```

https://docs.typo3.org/typo3cms/extensions/sms_responsive_images/DeveloperManual/Index.html#picturefill
