### ISSUE TITLE
Doesn't work with Typo3 9.1

### ISSUE THREAD

**Issue by rfc2822** [sitegeist/sms-responsive-images#30]
Hello,

Thanks for this plugin, which works perfectly with Typo3 8.7 here! Unfortunately, it doesn't seem to work with Typo3 9.1 anymore.

It complains about `this->objectManager` to be null. I have replaced this call by a new ObjectManager instance, but there are still errors.

In case I can provide more information, please let me know.

**Comment by s2b** [comment]
Could you check if the current master works for you?

```composer require sitegeist/sms-responsive-images dev-master```

**Comment by s2b** [comment]
Should be fixed with the latest version
