### ISSUE TITLE
Fallback src-attribute missing

### ISSUE THREAD

**Issue by jgrp** [sitegeist/sms-responsive-images#32]
I like your extension, after including the static tempaltes its working right away, like charm. 
As I saw on the documentation the default `src` attribute should be contained as fallback. 
I am using the default configurations and the `src` attribute is not showing up. 

```
<img 
 srcset="/fileadmin/_processed_/2/0/csm_flowers_01_ae8e56d053.png 400w, 
/fileadmin/_processed_/2/0/csm_flowers_01_d824802bcd.png 600w, 
/fileadmin/_processed_/2/0/csm_flowers_01_d42bc2d4a4.png 800w, 
/fileadmin/_processed_/2/0/csm_flowers_01_e1a70c84e6.png 1000w, 
/fileadmin/_processed_/2/0/csm_flowers_01_c0087add80.png 1200w, 
/fileadmin/_processed_/2/0/csm_flowers_01_4e626efa81.png 565w" 
 sizes="(min-width: 565px) 565px, 100vw" 
 width="565" 
 height="312">
```

Am I missing something?

**Comment by s2b** [comment]
Just set the `picturefill` attribute of the ViewHelper to `false` to generate markup with `src` attribute. However, if you use picturefill.js to support older browsers, you might consider omitting the attribute, as suggested by the documentation of picturefill.

https://docs.typo3.org/typo3cms/extensions/sms_responsive_images/DeveloperManual/Index.html#picturefill

**Comment by s2b** [comment]
Forgot to mention that this can also be set globally via TypoScript setup for default content elements (fluid_styled_content):

```
lib.contentElement.settings.tx_smsresponsiveimages.picturefill = 0
```
See: https://github.com/sitegeist/sms-responsive-images/blob/master/Configuration/TypoScript/Base/setup.ts

**Comment by jgrp** [comment]
That's it. Thanks!
