### ISSUE TITLE
scr attribute not working

### ISSUE THREAD

**Issue by anujaunds** [sitegeist/sms-responsive-images#34]
Hi,
I used this extension with my website but it's not working in internet explore properly. Becuase Img tag doesn't contain the Src attribute that s the reason. It's only work with srcset and internet explore doesn't support with srcset. for example:

<img
sizes="(max-width: 1920px) 100vw, 1920px"
srcset="
footer_rainbow_fjrr5j_c_scale,w_190.png 190w,
footer_rainbow_fjrr5j_c_scale,w_780.png 780w,
footer_rainbow_fjrr5j_c_scale,w_1190.png 1190w,
footer_rainbow_fjrr5j_c_scale,w_1920.png 1920w"
src="footer_rainbow_fjrr5j_c_scale,w_1920.png"
alt="">

**Comment by s2b** [comment]
If you want to support Internet Explorer, you should add the picturefill polyfill to your website. It adds the missing responsive images functionality to older browsers that don't support it.

http://scottjehl.github.io/picturefill/
