### ISSUE TITLE
Problem with AWS Images

### ISSUE THREAD

**Issue by 8bamo** [sitegeist/sms-responsive-images#35]
Chrome doesnt Support the Image-Path. How can I solve this ?
Im using <sms:media>

**Comment by s2b** [comment]
Can you give an example? Can you describe your setup (you mentioned AWS?)?

**Comment by 8bamo** [comment]
Sry for the late Response. It was my fault ^^ All the pictures loaded, but they had no width. 
But i got a other Problem now. Internet Explorer 11 is not supported ?

**Comment by 8bamo** [comment]
Thank you it worked!
