### ISSUE TITLE
Bad image quality PNG

### ISSUE THREAD

**Issue by josuavogel** [sitegeist/sms-responsive-images#47]
Hello,

I discovered, that PNG images have a bad quality. Every generated image looks red. All JPG images work fine.

Tested in TYPO3 9.5

**Comment by s2b** [comment]
Could you check if the test images in your Install Tool look right?

**Comment by josuavogel** [comment]
Yes, the test images look right. The original PNG images look also right, but the thumbnail inside the backend not.

**Comment by s2b** [comment]
That sounds like a configuration problem in TYPO3 or on the server. My extension only affects the frontend output of TYPO3 and doesn't change anything in the backend.
