### ISSUE TITLE
Question: Different crop variants for specific Fluid content elements

### ISSUE THREAD

**Issue by prookie** [sitegeist/sms-responsive-images#5]
Hi,

first of all, thank you for your awesome extension!

I want to be able to configure the crop variants not globally, but specific to multiple different Fluid content elements (FCEs).

Like for example:
- FCE A has crop variants 16:9 and 3:2
but
- FCE B has crop variants 16:9 and 1:1 (but 3:2 should not be visible/usable, and vice versa)

So i can **not** just do it like in the provided demo for altering the page media:

```
// Demo plugin: Enable three fixed crop variants for the page media field
$GLOBALS['TCA']['pages']['columns']['media']['config']['overrideChildTca']['columns']['crop']['config'] = [
    'cropVariants' => [
        'default' => [
            'disabled' => true
        ],
        'mobile' => [
            'title' => 'Mobile',
            'allowedAspectRatios' => [
                '1:1' => [
                    'title' => 'LLL:EXT:lang/Resources/Private/Language/locallang_wizards.xlf:imwizard.ratio.1_1',
                    'value' => 1
                ]
            ],
        ],
        'tablet' => [
            'title' => 'Tablet',
            'allowedAspectRatios' => [
                '4:3' => [
                    'title' => 'LLL:EXT:lang/Resources/Private/Language/locallang_wizards.xlf:imwizard.ratio.4_3',
                    'value' => 4 / 3
                ]
            ],
        ],
        'desktop' => [
            'title' => 'Desktop',
            'allowedAspectRatios' => [
                '16:9' => [
                    'title' => 'LLL:EXT:lang/Resources/Private/Language/locallang_wizards.xlf:imwizard.ratio.16_9',
                    'value' => 16 / 9
                ]
            ],
        ]
    ],
];
```

I guess I need to configure it for table `tt_content` somehow, but conditionally in respect to the content of the column `tx_fed_fcefile`, which will be something like _Vendor.Extname:ContentElementName.html_ in case of the row being a Fluid content element record.

Is there maybe any built-in way to solve this, or does someone have an idea how to approach this task?

**Comment by s2b** [comment]
The built-in way (as in built-in to the TYPO3 Core) would be to use the CType or list_type fields in tt_content to specify different TCA configurations for fields. However, you seem to be using Flux, with which I don't really have any experience...

This doesn't seem to be a problem with my extension but rather with the new TCA functionality in TYPO3 8.7, so I'd like to close this issue if that's ok with you?
