### ISSUE TITLE
Migrate to the original classes in namespace TYPO3Fluid\Fluid

### ISSUE THREAD

**Issue by julianhofmann** [sitegeist/sms-responsive-images#55]
Using Fluid Class Aliases has been deprecated in TYPO3 v9.5.

Instead of \TYPO3\CMS\Fluid\Core\ViewHelper\TagBuilder \TYPO3Fluid\Fluid\Core\ViewHelper\TagBuilder should be used.

**Comment by s2b** [comment]
Thanks! This will be part of the next major version of the extension, which I'm currently working on.

**Comment by s2b** [comment]
#56

**Comment by s2b** [comment]
This is already fixed in develop and will be part of v2.

**Comment by dsone** [comment]
The ELTS version of 8.7.x needs this change, too, where a necessary dependency update of typo3fluid/fluid (between 2.6.7 and 2.6.10) happens. Supposedly this dependency update is for 8.7.38 but happens on 8.7.37 when updating `typo3/cms --with-dependencies`, too.

Meaning TYPO3 ELTS v8.7.37 and newer will not be able to use this extension in v1.3.0.
Not sure that this is going to be fixed anymore, but a heads up.
