### ISSUE TITLE
Upscaled images when srcset bigger than image width

### ISSUE THREAD

**Issue by rupasix** [sitegeist/sms-responsive-images#57]
Typo3 9.5.13
plugin: 1.3.0
The plugin creates enlarged images when the srcset values are larger than the width of the original image. The same happens when I use the width or maxWidth parameter. I would expect that if the width of the original is exceeded, the original or image with the width / maxWidth parameter should be returned. In installtool I have processor_allowUpscaling disabled.

**Comment by rupasix** [comment]
Sorry, my mistake. After disabling processor_allowUpscaling I still had to delete all files from the _processed_ folder and it works ok. Now I have a problem the other way round - using the crop and breakpoints parameter together with width / maxWidth the original image for higher srcset is returned. I would expect maxWidth to be included here and used for breakpoints and srcset greater than this value. In the example below I use a 408px image, I gave it maxWidth 60px.

```
<picture>
  <source 
    srcset="
    /fileadmin/_processed_/4/a/csm_concept2_e7f721ce26.png 400w, 
    /fileadmin/_processed_/4/a/csm_concept2_bcdfe8394e.png 407w" 
    media="(min-width:1200px)" sizes="(min-width: 60px) 60px, 100vw">
  <source 
    srcset="/fileadmin/dummy/concept2.png 408w" 
    media="(min-width:768px)" sizes="(min-width: 60px) 60px, 100vw">
  <source 
    srcset="
    /fileadmin/_processed_/4/a/csm_concept2_ecb6b84ea0.png 400w, 
    /fileadmin/dummy/concept2.png 408w" sizes="100vw">
  <img class="image-embed-item" src="/fileadmin/_processed_/4/a/csm_concept2_9d83bdfe6f.png" alt="" width="60">
</picture>
```

Crop  breakpoints settings:
```
  0 {
    cropVariant = default
    media = (min-width:1200px)
    srcset = 1200,1600,1920
  }
  1 {
    cropVariant = tablet
    media = (min-width:768px)
    srcset = 800,1000
  }
  2 {
    cropVariant = mobile
    srcset = 400,600
    sizes = 100vw
  }
```

**Comment by rupasix** [comment]
I'm afraid it's my fault. I misunderstood <picture /> along with media,srcset and sizes. Additional images are created but using maxWidth will never be downloaded by the browser and this is the desired effect. I'm sorry for the trouble.

**Comment by s2b** [comment]
No problem. Sometimes it helps to just write it down. :-)
