### ISSUE TITLE
Use `.typoscript` rather than `.ts` for TypoScript configuration files.

### ISSUE THREAD

**Issue by LeoniePhiline** [sitegeist/sms-responsive-images#65]
Pity I didn't notice before 2.0 was released.

`.typoscript` is the new standard file extension. `.ts` anyway clashes with TypeScript.

**Comment by s2b** [comment]
You're right. Just to be sure: It works fine with `.ts`, it just doesn't use the TYPO3 standard, right? Which means that this doesn't need a hotfix but can wait until the next release?

**Comment by LeoniePhiline** [comment]
Yes, using semver this is a 3.0 breaking change.

`.ts` does work with TYPO3 10 as far as I can tell. It works with 10.3 and this should not change until the LTS.
