### ISSUE TITLE
Integrate `loading="lazy"` HTML5 standard.

### ISSUE THREAD

**Issue by LeoniePhiline** [sitegeist/sms-responsive-images#66]
Now supported by browsers (not yet Safari) and TYPO3 10 core:

Native lazyloading via `loading="lazy"`. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-loading

I believe there is no placeholder functionality in the standard, though.

**Comment by Patta** [comment]
@LeoniePhiline This can be done with `additionalAttributes="{loading: 'lazy'}"` in the viewHelper.

Example:
`<sms:image
        image="{file}"
        width="{dimensions.width}"
        height="{dimensions.height}"
        alt="{file.properties.alternative}"
        title="{file.properties.title}"
        srcset="380,520,680,800,1024,1200,1920"
        sizes="(min-width: %1$dpx) %1$dpx, 100vw"
        ignoreFileExtensions="svg,gif"
        additionalAttributes="{loading: 'lazy', draggable: 'false'}"
    />`

**Comment by LeoniePhiline** [comment]
Of course! How could I not see the obvious. 🙈
Thanks for the hint ^^
