### ISSUE TITLE
Filereference error in v2

### ISSUE THREAD

**Issue by Xippo** [sitegeist/sms-responsive-images#67]
Hi Folks, 

after the update on v2.0.1 the sms viewhelper fires errors if you try to render core or extbase Filereference Objects. In 1.3 it works fine.

Uncaught TYPO3 Exception: #1517766588: You must either specify a string src or a File object. | TYPO3Fluid\Fluid\Core\Exception thrown in file /xxx/typo3conf/ext/sms_responsive_images/Classes/ViewHelpers/ImageViewHelper.php in line 76.

**Comment by s2b** [comment]
Hi! Could you give me an example snippet? Also, which TYPO3 version are you using?

**Comment by s2b** [comment]
Well... I already have a hunch what's happening here. Could you test it with this branch?

https://github.com/sitegeist/sms-responsive-images/tree/bugfix/strictTypesTypo39

**Comment by Xippo** [comment]
Wow, that one was super fast reaction! It works like a charm. Thanks a lot for your work.
