### ISSUE TITLE
Namespace in image.html still the old one

### ISSUE THREAD

**Issue by rowild** [sitegeist/sms-responsive-images#73]
Hi!

I just updated to v2.0.2 and keep getting this error:
`get_class() expects parameter 1 to be object, null given in /[path]/typo3_src-9.5.21/typo3/sysext/fluid/Classes/ViewHelpers/MediaViewHelper.php line 110`

Upon reading the documentation I came accross the line that mentions that the namespace changed:
`The PHP namespace has switched from SMS\SmsResponsiveImages to Sitegeist\ResponsiveImages, so if you extended one of the provided PHP classes, you need to adjust this.`

But looking at the `image.html` in this extension, the namespace is still in the old fformat:
`<html xmlns:sms="http://typo3.org/ns/SMS/SmsResponsiveImages/ViewHelpers" data-namespace-typo3-fluid="true">`

Also, just updating from a v1 to a v2 does NOT remove the Demo folder. So reading the docu and comparing with the existing files in the extension is confusing :-)

**Comment by s2b** [comment]
It sounds like something went wrong in the composer (?) update process on your side. The demo folder is clearly not present in the released extension.

However, the namespace in the template file should be fixed, although the extension should work fine nontheless because of `ext_localconf.php`.
