### ISSUE TITLE
[BUG] Attributes loading and fileExtension are not in Typo3 v.9.5

### ISSUE THREAD

**Issue by rupasix** [sitegeist/sms-responsive-images#87]
Tested on:
Typo3 v9.5.31
EXT v.2.1.0
Hello! You assumed that attributes "loading" and "fileExtension" exists in "\TYPO3\CMS\Fluid\ViewHelpers\MediaViewHelper" but in typo3 v9 they don't. Viewhelper with new attributes is fired here https://github.com/sitegeist/sms-responsive-images/blob/master/Resources/Private/Extensions/fluid_styled_content/Partials/Media/Rendering/Image.html and it creates error:
```
Oops, an error occurred!
Undeclared arguments passed to ViewHelper Sitegeist\ResponsiveImages\ViewHelpers\MediaViewHelper: fileExtension, loading. Valid arguments are: additionalAttributes, data, class, dir, id, lang, style, title, accesskey, tabindex, onclick, alt, file, additionalConfig, width, height, cropVariant, srcset, sizes, breakpoints, lazyload, placeholderSize, placeholderInline, ignoreFileExtensions
```
Related commits:
https://github.com/sitegeist/sms-responsive-images/commit/a74d85fa3fbcafbcac1f1c9fbcfd3e802e9e5e4f
https://github.com/sitegeist/sms-responsive-images/commit/1a9a46ca68dde6e04b622b1fdebb62a356441e03

**Comment by s2b** [comment]
This should be fixed with v2.1.1 of the extension.
