### ISSUE TITLE
Idea: support webp extension as fallback

### ISSUE THREAD

**Issue by coarsy** [sitegeist/sms-responsive-images#90]
It would be great if the extension would support webp images from the web extension in the repository:

https://extensions.typo3.org/extension/webp

An additional param like "imagetype" could switch the image extension to webp.

**Comment by Gitsko** [comment]
that would also help me

**Comment by s2b** [comment]
This should already work with `fileExtension`

https://github.com/sitegeist/sms-responsive-images/blob/master/Classes/ViewHelpers/ImageViewHelper.php#L66
