### ISSUE TITLE
No scaling with empty `crop` (in TYPO3 v11)

### ISSUE THREAD

**Issue by julianhofmann** [sitegeist/sms-responsive-images#92]
If there's no cropping configured, `null` is passed as configuration in `$processingInstructions`. This way, the image is *not* scaled at all.

\Sitegeist\ResponsiveImages\Utility\ResponsiveImagesUtility:

            // Generate image
            $processingInstructions = [
                'width' => $candidateWidth,
                'crop' => $cropArea->isEmpty() ? null : $cropArea->makeAbsoluteBasedOnFile($image),
            ];

By unsettling `$processingInstructions['crop']` the utility works again.

TYPO3 11.5.3, sms_responsive_images v2.1.1

**Comment by s2b** [comment]
It seems strange to me that this is a problem with the extension because in the TYPO3 core the same snippet is used:
https://github.com/TYPO3/typo3/blob/master/typo3/sysext/fluid/Classes/ViewHelpers/Uri/ImageViewHelper.php#L153

Could you check if you have your problem there as well?

**Comment by julianhofmann** [comment]
Ok, it is really strange... This behavior, we have only when using the ViewHelper in a certain (custom) extension. 

Seems to be caused by the default `sizes="(min-width: %1$dpx) %1$dpx, 100vw"`... After some time of debugging, I'll "fix" it by setting the needed sizes.
