### ISSUE TITLE
placeholderInline + unscaleable main image = inline huge base64 main image

### ISSUE THREAD

**Issue by NamelessCoder** [sitegeist/sms-responsive-images#96]
We have a project which makes widespread use of the responsive image ViewHelper to scale images which are uploaded by the editors. Unfortunately we've noticed that a change in the use of the `placeholderInline` parameter has caused a bad side effect:

* Some images are reported by TYPO3 as not being possible to scale/resize (this is no fault of the sms package!)
* When these images are encountered, the sms package will use the original
* However, the `placeholderInline` boolean argument is passed to the image tag generating function also for the original image, making the original image also appear as base64-encoded inline
* This causes a huge chunk of base64-encoded data to be part of the page's generated source
* And this in turn puts a lot of pressure on the page cache which needs to hold records that in some cases are 10+ megabytes

The source of the problem seems to be that `placeholderInline`  is both used as it was intended - to make *placeholder* images inline - but also mistakenly still gets used to make any image inline, if the image could not be scaled.

The problem seems to exist in three places:

* https://github.com/sitegeist/sms-responsive-images/blob/2.1.2/Classes/Utility/ResponsiveImagesUtility.php#L77
* https://github.com/sitegeist/sms-responsive-images/blob/2.1.2/Classes/Utility/ResponsiveImagesUtility.php#L192
* https://github.com/sitegeist/sms-responsive-images/blob/2eb82c845edb0312d9861bc609eccf55365d8392/Classes/Utility/ResponsiveImagesUtility.php#L533

The first two would cause any image that has an ignored file extension to be rendered as inline (because $placeholderInline is passed as value of the $inline parameter also when the image is the original) and can likely be solved by simply not passing $placeholderInline to the function. The third place is a bit more hidden and not directly caused by the sms package - when ImageService->applyProcessingInstructions encounters an image that cannot be scaled (which includes but is not limited to formats like PDF and AI) the function returns an untouched original image which is then passed to the generateDataUri function. This in turn potentially causes huge image files which could not be scaled down, to become output as inline base64 code.

The first two are also relatively minor since they can indeed be avoided by adjusting the $ignoreFileExtensions argument, however, they should probably still be avoided through code since rendering the original image as inline base64 is probably never desirable. The third one however is difficult or impossible to work around (making TYPO3 think that a file that isn't detected as type=image through mime type is actually an image, is far from a simple matter - this is all TYPO3's fault and is a problem in any context where you attempt to scale a file that *can* be scaled but isn't *detected* as being an image, but unfortunately the sms package suffers indirectly from that problem).

Suggested fixes:

1. Do not pass $placeholderInline when rendering fallback images for ignored file extensions, or use only $fallbackImage and do not pass $originalImage in this case.
2. Check the returned File/ProcessedFile from ImageService->applyProcessingInstructions and ignore $inline in case the returned object is the original/unprocessed image.

**Comment by Atomschinken** [comment]
Hi @NamelessCoder,
i've added a PR with your proposed fix.
Could you please check if this solves your issue?

As i wasn't able to reproduce the described behavior on my local environment, this fix is untested for now.
Maybe you can help me out on this? Any hint would be much appreciated.

Thank you!

**Comment by infabo** [comment]
> However, the placeholderInline boolean argument is passed to the image tag generating function also for the original image, making the original image also appear as base64-encoded inline

Made this observation in the past as well. Result in an insane huge markup transfer from server to client.

**Comment by s2b** [comment]
I just released v2.1.3 which should resolve this issue.

**Comment by NamelessCoder** [comment]
Thank you @sb and @Atomschinken for the very quick reactions!
