### ISSUE TITLE
Apply selectedRatio if crop-attribute is set

### ISSUE THREAD

**Issue by sir-gawain** [sitegeist/sms-responsive-images#99]
If a crop configuration is given by the crop-attribute, the crop area must be set by hand to take effect in image rendering.
It is not possible to give a generic configuration and let the ImageViewHelper apply it.

This is because of `$cropArea->isEmpty()` check.

My scenario:

I have a frontend plugin, which allows users to create projects and upload images (any aspect ratio) to this projects. Then i want to list these projects and iterate over them. All "preview" images should have the same aspect ratio in the listview. This would be the perfect use case for a cropVariant. But! The crop configuration is set and calculated only in the backend by the image crop tool. So either i have to calculate the offsets myself on upload and save them to sys_file_reference to take effect while rendering the list, or i have to calculate the configuration at runtime and to provide individual crop-attributes while rendering the list. 

It would by cool to be able to to this:

```
<sms:image
    image="{images.0}"
    breakpoints="{settings.tx_smsresponsiveimages.breakpoints}"
    crop='{listview:{cropArea:{x:0,y:0,width:1,height:1},allowedAspectRatios:{vorschau:{title: "vorschau", value: 1.48}},selectedRatio:"vorschau"}}'
    cropVariant="listview"
/>
```

This is currently not possible, because of the mentioned `$cropArea->isEmpty()` check.

Archiving this is very simple:
add
`$cropVariantCollection = $cropVariantCollection->applyRatioRestrictionToSelectedCropArea($image);`

after creation of the cropVariantCollection (see bug #98)

```
$cropVariantCollection = CropVariantCollection::create(is_string($cropString) ? $cropString : json_encode($cropString));
$cropVariantCollection = $cropVariantCollection->applyRatioRestrictionToSelectedCropArea($image);
```

Done.

This should have no impact, if the correct cropVariantCollection is given by sys_file_reference, it would simply be recalculated. An attribute to enable this recalculation would by fine for me too.

**Comment by s2b** [comment]
Please let me know if this issue is still relevant

**Comment by sir-gawain** [comment]
This issue is not related to #98 (i only added the reference as the above code has my changes to json).
This issue is still not addressed.

**Comment by s2b** [comment]
Just to understand you correctly: Your suggestion is to implement this differently than it is in the core? I'm not sure this is a good idea because my intention was to stay compatible to the core ViewHelpers.

**Comment by sir-gawain** [comment]
Yes, i think it would be a nice addition to the extension. And as i said, i could live with a additional attribute to activate that behavour. I doesn't need to be active by default.

**Comment by sir-gawain** [comment]
I needed this again and came up with an solution without hacking the EXT. I wrote my own little viewhelper to create a non empty valid crop configuration from a template. I uploaded it to gist: [gist:3169488ddca9e8cbcb0361a469ae0bb8](https://gist.github.com/sir-gawain/3169488ddca9e8cbcb0361a469ae0bb8)

I don't need that request anymore.
